security:
    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory: { memory: ~ }

    firewalls:
        main:
            pattern: ^/
            anonymous: ~

    access_control:
