version: '2.1'

services:
    php:
        build:
            context: ./dockers/php7-fpm/
        env_file:
            ./.env
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www/current
        links:
            - maildev:mail.server

    nginx:
        build:
            context: ./dockers/nginx/
        ports:
            - "81:80"
        volumes_from:
            - php
        volumes:
            - ./var/log/nginx/:/var/log/nginx

    maildev:
        image: djfarrelly/maildev
        ports:
            - "1080:80"
            - "25"

    data:
        image: busybox
        volumes:
            - /var/lib/mysql

    sqlserver:
        image: mysql
        environment:
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
        volumes_from:
            - data
        ports:
            - "3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: sqlserver
            PMA_PORT: 3306
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - "3300:80"
        links:
            - sqlserver:data
