monolog:
    handlers:
        console:
            type: console
            process_psr_3_messages: false
        critical:
            type: fingers_crossed
            action_level: critical
            handler: grouped
        streamed:
            type:  stream
            path:  '%kernel.logs_dir%/%kernel.environment%.critical.log'
            level: debug
        grouped:
            type:    group
            members: [streamed, deduplicated]